name: Node.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # -------- CLIENT --------
      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Build client
        working-directory: ./client
        run: npm run build

      # -------- SERVER --------
      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Start server check
        working-directory: ./server
        run: echo "Server setup OK"
